### ISSUE TITLE
Documentation not complete

### ISSUE THREAD

**Issue by mkgrgis** [ibarwick/firebird_fdw#16]
Port option for foreign gerver + some notes about debian/ubuntu from https://github.com/ibarwick/firebird_fdw/pull/14/commits/4ce1f1a2bbd66f120432ee4b16cda937cb58a70e ( inside of https://github.com/ibarwick/firebird_fdw/pull/14 ).

**Comment by ibarwick** [comment]
Fixed, thanks for the report.

I'll update the source build instructions mentioned in #14 soon.
