### ISSUE TITLE
Do not exist library/package to postgresql12-firebird_fdw

### ISSUE THREAD

**Issue by maracarolinarojas** [ibarwick/firebird_fdw#18]
Hi. 

I run:  yum install postgresql12-firebird_fdw but as a result i got that do not exist package to postgresql12-firebird_fdw

Could you see this to? https://copr.fedorainfracloud.org/coprs/ibarwick/firebird_fdw/packages/

Could you help me?

**Comment by mkgrgis** [comment]
Logs are not available from https://copr.fedorainfracloud.org/coprs/ibarwick/firebird_fdw/build/918795/ or there is no public information about error. Maybe @ibarwick have access or this is an error of copr.fedorainfracloud.org.

It's not very hard to compile libfq and firebird_fdw. For example there was and there is no deb package for firebird_fdw and for Ubuntu compilation with make is necessary.

**Comment by ibarwick** [comment]
> Hi.
> 
> I run: yum install postgresql12-firebird_fdw but as a result i got that do not exist package to postgresql12-firebird_fdw
> 
> Could you see this to? https://copr.fedorainfracloud.org/coprs/ibarwick/firebird_fdw/packages/
> 
> Could you help me?

Fixed, thanks for the report.

**Comment by maracarolinarojas** [comment]
Thank you very much! it worked correctly now!
