### ISSUE TITLE
Undocumented feature or access error in firebird_version function

### ISSUE THREAD

**Issue by mkgrgis** [ibarwick/firebird_fdw#22]
This is about `SELECT * FROM firebird_version();` command.
There is 
```
SELECT fs.oid, fs.srvname, um.umuser
  FROM pg_foreign_data_wrapper fdw
 INNER JOIN pg_catalog.pg_foreign_server fs
       ON fs.srvfdw = fdw.oid
 INNER JOIN pg_catalog.pg_user_mapping um
       ON um.umserver=fs.oid
 WHERE fdw.fdwname = 'firebird_fdw'
```
query in algorithm of `firebird_version` function.
By default `pg_catalog.pg_user_mapping` isn't accessible for a users without superuser's rights. Non privileged user get `ERROR: no access to pg_user_mapping table`.

Steps to reproduce:
1. Make user without superuser's rights in Pg13.
2. Make DB for this user as owner.
3. From superuser. Create in the new DB of new user `firebird_fdw`extension and foreign server and user mapping for the user with the server.
4. Try to execute  `SELECT * FROM firebird_version();`.

**Comment by ibarwick** [comment]
Fixed, thanks for the report!

**Comment by mkgrgis** [comment]
Thanks, @ibarwick . I have verified on SQL level, no problem in selecting.
