### ISSUE TITLE
Question: Option to Force Conversion of Strings to a Specific Charset

### ISSUE THREAD

**Issue by HideyoshiNakazone** [ibarwick/firebird_fdw#43]
Hello, i would like very much to know if there is any option in this project that enables me to force the conversion of string to a specify charset when running `IMPORT SCHEMA`? 
If not, is there any alternatives? Or would you recommend me somewhere to start to implement this feature?

Thank you very much,
Vitor Hideyoshi.

**Comment by HideyoshiNakazone** [comment]
Being a little more specific about my problem, i need to import data from a Firebird database that uses `iso8859_1` to `utf8`. Any suggestions are very much welcome.

**Comment by mkgrgis** [comment]
Hello, @HideyoshiNakazone ! This FDW implements ISO:SQL recommendations and treat FirebirdSQL text data only according stored encoding info in `.fdb` metadata or as PostgreSQL `SQL_ASCII` encoding if there is `NONE` character set value. Please read https://github.com/ibarwick/firebird_fdw#character-set-handling No additional options are available. If there is no proper metadata in a `.fdb` this is only problem of ugly Firebird usage.

**Comment by HideyoshiNakazone** [comment]
Thank you very much for the response, i didn't know that the metadata of the `.fdb` file was read. I just received the file by a client and i didn't know that was a thing.
Again, thank you very much!
